language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TORCH_VERSION=1.2
  - TORCH_VERSION=1.3
  - TORCH_VERSION=1.4
  - TORCH_VERSION=1.5
jobs:
  exclude:
    - python: "3.8"
      env: TORCH_VERSION=1.2
    - python: "3.8"
      env: TORCH_VERSION=1.3
install:
  - bash .travis.install
script:
  - make ci
cache:
  directories:
    - /home/travis/.cache/
