language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TORCH_VERSION=1.2
  - TORCH_VERSION=1.3
  - TORCH_VERSION=1.4
  - TORCH_VERSION=1.5
install:
  - python3 -m pip install -r requirements/ci-base.txt
script:
  - make ci
cache:
  directories:
    - /home/travis/.cache/
